name: pop_pop_win
author: Dart Team <misc@dartlang.org>
description: '"Pop, Pop, Win!" is an implementation of Minesweeper in Dart.'
homepage: https://github.com/dart-lang/sample-pop_pop_win
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  bot: '^0.28.0'
  browser: '^0.10.0'
  chrome: '^0.6.3'
  stagexl: '^0.11.0'
dev_dependencies:
  test: '^0.12.0'
