name: pop_pop_win
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  js: ^0.6.1
  stagexl: ^2.1.1

dev_dependencies:
  build_runner: ^2.0.1
  build_web_compilers: ^4.0.0
  dart_flutter_team_lints: ^2.0.0
  preload: ^2.0.0
  test: ^1.0.0
